### ISSUE TITLE
Figures need to be editable, high resolution etc

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy#144]
Please see the message below from Alan Stonebraker at ARAA: we have some work to do on our figures! Perhaps we can divide the work between us? 

Dear Dr. Marshall, 

As the Illustration Editor for the Annual Review of Astronomy and Astrophysics, I’m looking forward to working with you to assure that the figures in your article are satisfactory to you and also meet our visual standards. Annual Reviews treats figures somewhat differently from many other journals: we work with your figures to ensure that text is legible and consistent, colors are used to maximum advantage, and figures are overall as clear and excellent as they can be.

I've just looked over the figures you submitted, and I see that they are in flattened raster format, so that none of the individual elements can be edited or scaled separately. Because I will need to make house style changes to fonts, capitalization, color, and the like, I'm hoping to get the images in the original editable format you used to create them, with vector components and/or layers that can be independently manipulated. Editable text is especially important. If vector graphics are not available, please send high-resolution versions (at least 300 dpi at desired final print dimensions).

The figures I need in a vector format or higher resolution are Figures 1 through 4. 

Preferred formats: 
- If you created the files in Adobe Illustrator, please send the original .ai or .eps files. Make sure images are embedded, not linked.
- If you created them in Photoshop, please send LAYERED .psd or .tif files, with text on a separate layer from the images. Or send the photos without the text and lines and I will add these in the correct style. (Minimum resolution: 300 dpi at final print size.)
- If you created them in PowerPoint, please send the original .ppt file(s). 
- If you used a different program, such as Freehand, Canvas, CorelDraw, Arc, CAD, or ChemDraw, please use "Save As" or "Export" to convert these to a vector format I can then easily edit (.ai, .eps, .pdf, .ps, or .wmf). Often one can print to PDF format as well: choose "print" but select "PDF file" as the destination instead of your printer. 

[NOTE: If you obtained the figures from an online version of a journal, you will most likely need to contact the paper's author(s) to obtain original high-quality files (which can be done at the same time that permission to reprint is obtained). The versions of figures found online are typically compressed, flattened, low resolution, and otherwise unsuitable for our book-quality printing.]

Our Author Graphics Guide, which explains the terms raster and vector, is available at https://www.annualreviews.org/page/authors/author-instructions/preparing/gguide if you need additional information.

To send the files, you may email me attachments up to 50 MB per message. Or you may place files on my graphics FTP site; please let me know if you'd like to upload files in this manner and I will send along instructions.

Please don't hesitate to contact me if there is anything I can do to explain or assist.

Thanks in advance for your help, 

Alan

**Comment by chrislintott** [comment]
Sorted for Figures 1-3. Phil, figure 4 is up to you.

**Comment by drphilmarshall** [comment]
Unless we get a rejection notice, I think this is closed...
