### ISSUE TITLE
Sign and return ARAA copyright forms

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy#146]
To be checked in and filled out by each of us. 

* [x] [Phil](https://github.com/drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy/raw/master/proofs/AA_Forms_AU-Marshall.pdf)
* [x] [Leigh](https://github.com/drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy/raw/master/proofs/AA_Forms_CoAU-Fletcher.pdf)
* [x] [Chris](https://github.com/drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy/raw/master/proofs/AA_Forms_CoAU-Lintott.pdf)

**Comment by chrislintott** [comment]
Done!

**Comment by drphilmarshall** [comment]
Done! @leighfletcher have you sent back your ARAA copyright forms yet? Thanks!

**Comment by drphilmarshall** [comment]
Closed via Leigh's email.
